/* Generated By: CSCC: 4.0 (03/25/2012)  Do not edit this line. TheParserConstants.cs */
using System;
public class TheParserConstants {

  public const int EOF = 0;
  public const int LC = 8;
  public const int RC = 9;
  public const int LP = 10;
  public const int RP = 11;
  public const int LB = 12;
  public const int RB = 13;
  public const int CLASS = 14;
  public const int ASS = 15;
  public const int C = 16;
  public const int SC = 17;
  public const int DOT = 18;
  public const int DO = 19;
  public const int IF = 20;
  public const int COMMA = 21;
  public const int ELSE = 22;
  public const int NULL = 23;
  public const int INH = 24;
  public const int NEW = 25;
  public const int RTN = 26;
  public const int WHILE = 27;
  public const int BOOL = 28;
  public const int NUMBER = 29;
  public const int BID = 30;
  public const int SID = 31;
  public const int SYMBOLS = 32;
  public const int D = 33;
  public const int L = 34;
  public const int BL = 35;
  public const int SL = 36;
  public const int S = 37;
  public const int CHAR = 38;
  public const int STRING = 39;

  public const int DEFAULT = 0;

  public String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"class\"",
    "\"=\"",
    "\":\"",
    "\";\"",
    "\".\"",
    "\"do\"",
    "\"if\"",
    "\",\"",
    "\"else\"",
    "\"null\"",
    "\"inherits\"",
    "\"new\"",
    "\"return\"",
    "\"while\"",
    "<BOOL>",
    "<NUMBER>",
    "<BID>",
    "<SID>",
    "<SYMBOLS>",
    "<D>",
    "<L>",
    "<BL>",
    "<SL>",
    "<S>",
    "<CHAR>",
    "<STRING>",
  };

}
